name: cuatrochenta_weather_rodrigo
description: Prueba Técnica 480 - Rodrigo Ballesteros Cabañas
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  flutter_screenutil: ^5.6.0
  flutter_native_splash: ^2.2.3
  freezed_annotation: any
  device_info_plus: ^4.1.2
  package_info_plus: ^1.3.0
  json_annotation: ^4.4.0
  http: ^0.13.4
  lottie: ^1.3.0
  rxdart: ^0.27.2
  animate_do: ^2.0.0
  intl: ^0.17.0
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  freezed: any
  build_runner: any
  json_serializable: any
  dart_code_metrics: ^4.8.1
  change_app_package_name: ^1.0.0
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/background.png"
  adaptive_icon_foreground: "assets/icon/foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/images/png/2x/
    - assets/images/png/3x/
    - assets/lotties/